from abc import ABC, abstractmethod

class SimulatorBackend(ABC):
    """Interface dasar untuk backend simulasi OM1."""
    @abstractmethod
    def connect(self): ...
    @abstractmethod
    def send_command(self, cmd: dict): ...
    @abstractmethod
    def get_state(self) -> dict: ...
    @abstractmethod
    def disconnect(self): ...
